import assert from 'node:assert/strict';
import test from 'node:test';
import {mkdtemp,rm,readFile,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createModelAdmission} from '../src/model-admission.ts';
import {loadModelProfiles} from '../src/model-profiles.ts';
test('catalog admission adds an exact priced host model, preserves prior tariffs and never stores a credential or accepts a client endpoint',async()=>{
 const root=await mkdtemp(join(tmpdir(),'hq-model-admit-')),hostFile=join(root,'host.json'),file=join(root,'operator.json'),oldPath=process.env.HQ_MODEL_PROFILES_PATH,oldKey=process.env.HQ_TEST_PROVIDER_KEY;process.env.HQ_MODEL_PROFILES_PATH=hostFile;process.env.HQ_TEST_PROVIDER_KEY='host-secret-not-for-state';
 try{const host={provider:'configured',model:'existing',format:'chat',endpoint:'https://provider.example/v1',keyEnv:'HQ_TEST_PROVIDER_KEY',pricing:{tokensPerBlock:'1000000',inputNanodollars:'125000000',outputNanodollars:'250000000',cachedInputNanodollars:'25000000'},maxInputTokens:32000,maxOutputTokens:100};await writeFile(hostFile,JSON.stringify([host]));const initial=await loadModelProfiles(),manager=createModelAdmission(file,initial),input={provider:'configured',model:'new',maxInputTokens:32000,maxOutputTokens:100,pricing:{tokensPerBlock:'1000000',inputNanodollars:'123456789',outputNanodollars:'987654321',cachedInputNanodollars:'12345678'}};
 await assert.rejects(manager.admit(input),/catalog/);manager.noteCatalog('configured',[{id:'new'},{id:'another'}]);await assert.rejects(manager.admit({...input,model:'not-in-catalog'}),/catalog/);await assert.rejects(manager.admit({...input,pricing:{...input.pricing,inputNanodollars:'0.01'}}),/exact/);
 const previous=initial.find(p=>p.provider.name==='configured')!.options.meteredPricing!;await manager.admit({...input,endpoint:'https://attacker.invalid',keyEnv:'OTHER_KEY',apiKey:'client-secret'});const profile=manager.profiles().find(p=>p.provider.name==='configured'&&p.options.model==='new')!;assert.equal(profile.options.meteredPricing!.inputNanodollars,123456789n);assert.equal(profile.options.maxInputTokens,32000);assert.equal(profile.hostConfig!.endpoint,host.endpoint);assert.deepEqual(manager.profiles().find(p=>p.provider.name==='configured'&&p.options.model==='existing')!.options.meteredPricing,previous);
 const bytes=await readFile(file,'utf8');assert.doesNotMatch(bytes,/host-secret|client-secret|attacker|OTHER_KEY/);assert.match(bytes,/HQ_TEST_PROVIDER_KEY/);assert.equal((await loadModelProfiles(file)).find(p=>p.options.model==='new')!.options.meteredPricing!.outputNanodollars,987654321n);
 await assert.rejects(manager.admit(input),/immutable/);const outcomes=await Promise.allSettled([manager.admit({...input,model:'another'}),manager.admit({...input,model:'another'})]);assert.equal(outcomes.filter(o=>o.status==='fulfilled').length,1);assert.equal(JSON.parse(await readFile(file,'utf8')).length,2);
 }finally{if(oldPath===undefined)delete process.env.HQ_MODEL_PROFILES_PATH;else process.env.HQ_MODEL_PROFILES_PATH=oldPath;if(oldKey===undefined)delete process.env.HQ_TEST_PROVIDER_KEY;else process.env.HQ_TEST_PROVIDER_KEY=oldKey;await rm(root,{recursive:true,force:true});}
});
