import {randomUUID} from 'node:crypto';
import {join} from 'node:path';
import {readdir} from 'node:fs/promises';
import {ids,money,currencyCode} from '@hqoverlord/core';
import {correlationId} from '@hqoverlord/events';
import {workspaceKey,AuthorityStore,DurableRuntime,FileDurableStore,systemClock,systemIds,commandId,ToolRegistry,createWebReadTool,notebookTools,skillTools,registerStationTools,registerBrowserTools,registerCommsTools,createStationAttachments,createStationFileReader,createStationWorkshop,OpenAIModelProvider,ReferenceModelProvider,memoryContext,validateMeteredPricing,type CommandContext,type ModelExecutionOptions} from '@hqoverlord/runtime';
import {createControlCentre} from '../../control-centre/src/server.ts';
import {projectBusiness} from '../../control-centre/src/projection.ts';
import {startChannelHosts} from '../../control-centre/src/channel-hosts.ts';
import {startMcpHosts} from '../../control-centre/src/mcp-hosts.ts';
import {loadWebKeys} from '../../control-centre/src/web-keys.ts';
export interface BrainConfig {provider:string;model:string;format:'responses'|'chat'|'anthropic'|'gemini'|'openrouter';endpoint:string;keyEnv?:string;pricing:{tokensPerBlock:string;inputNanodollars:string;outputNanodollars:string;cachedInputNanodollars:string};budgetCents:string;}
export interface HQProfile {name:string;skin:number;agentId?:string;businesses:{id:string;name:string}[];layouts:Record<string,unknown>;brain?:BrainConfig;brains?:BrainConfig[];}
export async function stationHost(root:string,scope:{id:string;name:string},getProfile:()=>HQProfile|undefined,getKey:(provider?:string)=>string){
 const businessId=ids.business(scope.id),store=new FileDurableStore(join(root,scope.id,'state.json'));let state=await store.load();
 if(!state.authority.businesses.length){const authority=new AuthorityStore(state.authority),now=systemClock.now();authority.addBusiness({id:businessId,name:scope.name,status:'active',createdAt:now,updatedAt:now});await store.save({...state,authority:authority.snapshot()});}
 const runtime=await DurableRuntime.open(store,systemClock,systemIds);
 const context=():CommandContext=>({businessId,commandId:commandId(randomUUID()),correlationId:correlationId(randomUUID()),principal:{kind:'human',id:'hq.operator'}});
 await runtime.ensureStation(context());
 await runtime.reconcileFloorWork({...context(),principal:{kind:'system',id:'hq.runtime'}});
 await runtime.reconcileStandingLoops({...context(),principal:{kind:'system',id:'hq.runtime'}});
 const tools=new ToolRegistry();tools.register(createWebReadTool());for(const t of [...notebookTools(runtime),...skillTools(runtime)])tools.register(t);
 const workspaces=join(root,scope.id,'workspaces');registerStationTools(runtime,tools,workspaces,{webKeyFor:await loadWebKeys()});const browsers=registerBrowserTools(tools,join(root,scope.id,'browser-profiles'),{workspaceRoot:workspaces});
 const attachments=createStationAttachments(runtime,workspaces);let channels:Awaited<ReturnType<typeof startChannelHosts>>|undefined;
 registerCommsTools(runtime,tools,workspaces,()=>channels);
 const connectors=process.env.HQ_ENABLE_CONNECTORS==='1'?await startMcpHosts(runtime,context(),tools):undefined;
 const configuredBrains=()=>getProfile()?.brains??(getProfile()?.brain?[getProfile()!.brain!]:[]);function enabled(){return configuredBrains().some(brain=>!!(getKey(brain.provider)||(brain.keyEnv&&process.env[brain.keyEnv])||['127.0.0.1','localhost','[::1]'].includes(new URL(brain.endpoint).hostname)));}
 const run=async(c:CommandContext,id:string,reasonOnly?:boolean)=>{const selected=runtime.inspectModelAccount(c,ids.job(id))?.policy??runtime.station(c).profiles.find(p=>p.agentId===runtime.inspectJob(c,ids.job(id)).agentId)?.model;const brain=selected?configuredBrains().find(b=>b.provider===selected.provider&&b.model===selected.model):getProfile()?.brain;if(!brain||!enabled())throw new Error('Connect the selected model in Models before executing work.');const apiKey=['127.0.0.1','localhost','[::1]'].includes(new URL(brain.endpoint).hostname)?'':getKey(brain.provider)||(brain.keyEnv?process.env[brain.keyEnv]:'')||'';const provider=brain.format==='responses'?new OpenAIModelProvider({apiKey}):new ReferenceModelProvider({name:brain.provider,format:brain.format,endpoint:brain.endpoint,...(apiKey?{apiKey}:{})});const pricing={version:1 as const,currency:'USD' as const,unit:'nanodollar' as const,provider:brain.provider,model:brain.model,tokensPerBlock:BigInt(brain.pricing.tokensPerBlock),inputNanodollars:BigInt(brain.pricing.inputNanodollars),outputNanodollars:BigInt(brain.pricing.outputNanodollars),cachedInputNanodollars:BigInt(brain.pricing.cachedInputNanodollars)};validateMeteredPricing(pricing);const job=runtime.inspectJob(c,ids.job(id));const options:ModelExecutionOptions={model:brain.model,meteredPricing:pricing,budget:money(BigInt(brain.budgetCents),currencyCode('USD')),maxInputTokens:4096,maxOutputTokens:1024,maxTurns:12,maxRetries:2,...(job.agentId?{inputContent:await attachments.expand(c,job.agentId,(runtime.snapshot().artifacts??[]).filter(a=>a.jobId===job.id).flatMap(a=>(a.content as {attachments?:import('@hqoverlord/runtime').StationAttachment[]}).attachments??[])) as import('@hqoverlord/runtime').ModelRequest['inputContent']}: {})};try{return await runtime.executeModelJob(c,job.id,provider,reasonOnly?new ToolRegistry():tools,options);}finally{if(runtime.inspectJob(c,job.id).status!=='running')await browsers.release(job.id);}};
 let refresh=()=>{};channels=process.env.HQ_ENABLE_CHANNELS==='1'?await startChannelHosts(runtime,context(),run,()=>refresh(),attachments,()=>configuredBrains().map(b=>({provider:b.provider,model:b.model}))):undefined;
 memoryContext.setKnownSecretSource(()=>[...configuredBrains().map(b=>getKey(b.provider)),...Object.entries(process.env).filter(([n,v])=>v&&/(KEY|TOKEN|SECRET|PASSWORD)/.test(n)).map(([,v])=>v!)].filter(Boolean));
 const app=createControlCentre({runtime,businessIds:[businessId],context,assetRoot:new URL('../public/',import.meta.url),get modelEnabled(){return enabled();},models:()=>configuredBrains().map(b=>({provider:b.provider,model:b.model})),get metadata(){return {[businessId]:{identity:{name:scope.name},budgets:{perJobUsdLimit:money(BigInt(getProfile()?.brain?.budgetCents??'100'),currencyCode('USD'))}}};},attachment:attachments.save,file:createStationFileReader(runtime,workspaces),workshop:createStationWorkshop(runtime,workspaces,join(root,scope.id,'outbox')),channelStatus:()=>channels?.status()??[],...(connectors?{connectorCatalog:()=>connectors.catalog(),installConnector:connectors.install}:{}),run});refresh=app.refresh;
 await new Promise<void>((resolve,reject)=>{app.server.once('error',reject);app.server.listen(0,'127.0.0.1',resolve);});const port=(app.server.address() as {port:number}).port;const handshake=await fetch('http://127.0.0.1:'+port+'/');await handshake.arrayBuffer();const cookie=handshake.headers.get('set-cookie')!.split(';')[0];
 return {runtime,context,port,cookie,refresh,listFiles:async(agentId:string)=>{const agent=runtime.effectiveAgent(context(),ids.agent(agentId)),base=join(workspaces,workspaceKey({businessId,agent}));const files:string[]=[];async function walk(path:string,prefix='',depth=0):Promise<void>{if(depth>8||files.length>=1000)return;let entries;try{entries=await readdir(path,{withFileTypes:true});}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')return;throw error;}for(const entry of entries){if(entry.isSymbolicLink()||entry.name.startsWith('.'))continue;const relative=prefix+entry.name;if(entry.isFile())files.push(relative);else if(entry.isDirectory())await walk(join(path,entry.name),relative+'/',depth+1);if(files.length>=1000)break;}}await walk(base);return files;},snapshot:()=>projectBusiness(runtime.snapshot(),businessId,new Set(runtime.snapshot().authority.jobs.filter(j=>runtime.isJobActive(context(),j.id)).map(j=>j.id))),close:async()=>{channels?.close();connectors?.close();await browsers.close();await app.close();}};
}
