import {createRequire} from 'node:module';
import type {AgentId,JobId} from '@hqoverlord/core';
import {commandId,type CommandContext} from './command-context.ts';
import type {DurableRuntime} from './durable-runtime.ts';
import type {DurableState} from './durable-state.ts';
import type {ExecutionResult} from './execution-contracts.ts';
const require=createRequire(import.meta.url);
export interface StandingIteration {readonly n:number;readonly runId:JobId;readonly startedAt:string;readonly endedAt:string|null;readonly outcome:'running'|'candidate'|'noop'|'red'|'failed'|'cancelled';readonly verdict:'approved'|'rejected'|'discarded'|null;readonly title?:string|null;readonly summary?:string|null;readonly error?:string|null;readonly verdictNote?:string|null;readonly usd?:number;readonly files?:readonly {path:string;bytes:number|null}[];}
export interface StandingLoop {readonly id:string;readonly name:string;readonly objective:string;readonly agentId:AgentId;readonly enabled:boolean;readonly state:'idle'|'running'|'waiting'|'paused'|'dormant'|'stopped'|'done';readonly gate:'review'|'auto';readonly stopReason:string|null;readonly iterationCount:number;readonly iterations:readonly StandingIteration[];readonly maxIterations:number|null;readonly fireClaim:number|null;readonly heartbeatAt:number|null;readonly budget:{readonly perDayUsd:number;readonly perIterationUsd:number;readonly spentTodayUsd:number;readonly day:number};readonly exactBudget:{readonly perDayCents:bigint;readonly perIterationCents:bigint};}
export interface StandingLoopSpec {readonly id:string;readonly name:string;readonly objective:string;readonly agentId:AgentId;readonly gate:'review'|'auto';readonly queueCap:number;readonly maxIterations:number;readonly dryStopAfter:number;readonly perDayCents:bigint;readonly perIterationCents:bigint;}
export const loopPolicy=require('../vendor/starnet/sidecar/loopjob.js') as {decide(loop:StandingLoop,input:unknown,context:unknown):{fire:boolean;binding:string|null};digest(loop:StandingLoop,context:unknown):string;pendingReviews(loop:StandingLoop):StandingIteration[];stackedAbove(loop:StandingLoop,n:number):StandingIteration[];};
export const loopStore=require('../vendor/starnet/sidecar/loopjob-store.js') as {createLoop(loops:readonly StandingLoop[],spec:unknown,ctx:unknown):StandingLoop[];updateLoop(loops:readonly StandingLoop[],id:string,patch:unknown,ctx:unknown):StandingLoop[];claimFire(loops:readonly StandingLoop[],id:string,ctx:unknown):StandingLoop[];startIteration(loops:readonly StandingLoop[],id:string,ctx:unknown):StandingLoop[];settleIteration(loops:readonly StandingLoop[],id:string,result:unknown,ctx:unknown):StandingLoop[];recoverInterruptedIteration(loops:readonly StandingLoop[],id:string,reason:string,ctx:unknown):StandingLoop[];pauseLoop(loops:readonly StandingLoop[],id:string,reason:string,ctx:unknown):StandingLoop[];resumeLoop(loops:readonly StandingLoop[],id:string,ctx:unknown):StandingLoop[];stopLoop(loops:readonly StandingLoop[],id:string,reason:string,ctx:unknown):StandingLoop[];recordVerdict(loops:readonly StandingLoop[],id:string,n:number,verdict:string,ctx:unknown):StandingLoop[];};
export function validateStandingLoops(loops:readonly StandingLoop[],state:DurableState,businessId:string){const refuse=()=>{throw new TypeError('Invalid durable standing loop');};if(!Array.isArray(loops)||loops.length>100||new Set(loops.map(l=>l.id)).size!==loops.length)refuse();for(const l of loops){
 if(!l||typeof l.id!=='string'||!/^[A-Za-z0-9_-]{1,40}$/.test(l.id)||typeof l.name!=='string'||typeof l.objective!=='string'||!l.objective.trim()||l.objective.length>4000||!state.authority.agents.some(a=>a.id===l.agentId&&a.businessId===businessId)||typeof l.enabled!=='boolean'||!['review','auto'].includes(l.gate)||!['idle','running','waiting','paused','dormant','stopped','done'].includes(l.state)||!Number.isSafeInteger(l.iterationCount)||l.iterationCount<0||!l.exactBudget||[l.exactBudget.perDayCents,l.exactBudget.perIterationCents].some(n=>typeof n!=='bigint'||n<0n||n>100000000n)||!Array.isArray(l.iterations))refuse();
 if(new Set(l.iterations.map(i=>i.n)).size!==l.iterations.length)refuse();for(const i of l.iterations)if(!Number.isSafeInteger(i.n)||i.n<1||i.n>l.iterationCount||!state.authority.jobs.some(j=>j.id===i.runId&&j.agentId===l.agentId&&j.businessId===businessId)||!['running','candidate','noop','red','failed','cancelled'].includes(i.outcome)||!Number.isFinite(Date.parse(i.startedAt))||i.endedAt!==null&&!Number.isFinite(Date.parse(i.endedAt)))refuse();
 // This composition deliberately has no unchecked host project-root/command authority.
 if((l as unknown as {workdir?:unknown;checkCmd?:unknown}).workdir||(l as unknown as {checkCmd?:unknown}).checkCmd)refuse();
 }}
const leases=new WeakMap<DurableRuntime,Set<string>>();
/** Short atomic admission; each real standing iteration runs independently outside the state transaction. */
export async function runStandingLoopTick(runtime:DurableRuntime,context:CommandContext,execute:(context:CommandContext,jobId:JobId)=>Promise<ExecutionResult>):Promise<void>{
 let held=leases.get(runtime);if(!held){held=new Set();leases.set(runtime,held);}const work:Promise<void>[]=[];
 for(const loop of runtime.station(context).loops??[]){const key=JSON.stringify([context.businessId,loop.id]);if(held.has(key))continue;
 const running=loop.iterations.findLast(i=>i.outcome==='running');if(running){const job=runtime.inspectJob(context,running.runId);if(['completed','failed','cancelled'].includes(job.status))await runtime.settleStandingLoop(context,loop.id,job.id);continue;}
 const job=await runtime.claimStandingLoop(context,loop.id);if(!job)continue;held.add(key);
 work.push(Promise.resolve().then(()=>execute({...context,commandId:commandId('loop-run:'+job.id)},job.id)).then(async outcome=>{if(outcome.status!=='waiting_for_approval')await runtime.settleStandingLoop(context,loop.id,job.id);},async()=>{if(['queued','running'].includes(runtime.inspectJob(context,job.id).status))await runtime.cancelJob({...context,commandId:commandId('loop-failed:'+job.id)},job.id);await runtime.settleStandingLoop(context,loop.id,job.id);}).finally(()=>held!.delete(key)));
 }await Promise.all(work);
}
